#!/usr/bin/env bash
set -e -u

# Check for input file or -h
if [[ -z ${1-} || ${1} == '-h' ]]; then
    echo "Usage: apt-get-url <url of file to download and install>"
    exit 1
fi

# Check that we're root
if [[ ${UID} -ne 0 ]]; then
    echo "You must be root to run this utility"
    exit 2
fi

# set up the variables
FILEURL=${1}
FILENAME=${FILEURL##*/}

# get the file
curl -o /tmp/${FILENAME} ${FILEURL}

# install the file
if [[ $(which gdebi) ]]; then
    gdebi /tmp/${FILENAME}
else
    apt-get install -y gdebi
    gdebi --non-interactive /tmp/${FILENAME}
fi

# tidy up
rm /tmp/${FILENAME}

echo "Done!"
