#!/usr/bin/env bash
set -e -u
if [[ -z "${1-}" || "${1}" == '-h' ]]; then
    echo "Usage: dl <url of file to download>"
    exit 1
fi
FILEURL=${1}
FILENAME=${FILEURL##*/}
curl -o ${FILENAME} ${FILEURL}
